//! Build script for the Dioxus app crate.
//!
//! Two responsibilities:
//! 1. Ensure `assets/tailwind.css` exists as a placeholder so `cargo check`
//!    can resolve `asset!("/assets/tailwind.css")` even on a fresh clone.
//!    `dx serve` / `dx build` overwrites this placeholder with compiled CSS.
//! 2. Scan `assets/wiki-art/{characters,weapons}/*.png` and emit a match
//!    table mapping basename → `asset!("/assets/wiki-art/<dir>/<name>.png")`
//!    into `$OUT_DIR/wiki_art_match.rs`. The runtime module
//!    `src/assets_wiki.rs` includes this via `include!`.

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir = PathBuf::from(
        env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"),
    );
    ensure_tailwind_stub(&manifest_dir);
    emit_wiki_art_match(&manifest_dir);
}

fn ensure_tailwind_stub(manifest_dir: &std::path::Path) {
    let out_css = manifest_dir.join("assets").join("tailwind.css");
    if !out_css.exists() {
        fs::write(
            &out_css,
            "/* placeholder — `dx serve` regenerates this from tailwind.css */\n",
        )
        .expect("write tailwind.css stub");
    }
    println!("cargo:rerun-if-changed=tailwind.css");
}

fn emit_wiki_art_match(manifest_dir: &std::path::Path) {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    let wiki_art = manifest_dir.join("assets").join("wiki-art");

    let mut body = String::new();
    body.push_str("// @generated by build.rs — do not edit.\n");
    body.push_str("use dioxus::prelude::*;\n\n");

    emit_lookup(
        &mut body,
        &wiki_art.join("characters"),
        "/assets/wiki-art/characters",
        "character_asset",
    );
    emit_lookup(
        &mut body,
        &wiki_art.join("weapons"),
        "/assets/wiki-art/weapons",
        "weapon_asset",
    );

    let out_file = out_dir.join("wiki_art_match.rs");
    fs::write(&out_file, body).expect("write wiki_art_match.rs");

    println!("cargo:rerun-if-changed=assets/wiki-art");
}

fn emit_lookup(
    out: &mut String,
    dir: &std::path::Path,
    url_prefix: &str,
    fn_name: &str,
) {
    let mut names: Vec<String> = fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", dir.display()))
        .filter_map(|r| r.ok())
        .filter(|e| {
            e.path()
                .extension()
                .map(|ext| ext == "png")
                .unwrap_or(false)
        })
        .map(|e| e.path().file_stem().unwrap().to_string_lossy().to_string())
        .collect();
    names.sort();

    out.push_str(&format!(
        "pub fn {fn_name}(name: &str) -> Option<Asset> {{\n    Some(match name {{\n"
    ));
    for n in &names {
        out.push_str(&format!(
            "        {:?} => asset!(\"{}/{}.png\"),\n",
            n, url_prefix, n
        ));
    }
    out.push_str("        _ => return None,\n    })\n}\n\n");
}
